- name: Ansible Copy Local to Remote
  hosts: "{{hosts}}"
  vars:
    src_path: /var/lib/jenkins/workspace/real-world-cicd/webapp/target/webapp.war"
    dest_path: "/opt/tomcat/webapps"
  tasks:
    - name: copying file with playbook
      become: true
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: ansibleadmin
        group: ansibleadmin
        mode: 0644