---
- name: Ansible Copy Local to Remote
  hosts: dev
  vars:
    src_path: "{{ workspace_path }}/webapp/target/webapp.war"
    dest_path: /var/lib/tomcat/webapps
    config_file_src_path: "{{ workspace_path }}/{{ hosts }}-config.yaml"
    config_file_dest_path: /home
  tasks:
    - name: Copying WAR file to Tomcat webapps directory
      become: true
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: ansibleadmin
        group: ansibleadmin
        mode: "0644"
    - name: Copying configuration file
      become: true
      copy:
        src: "{{ config_file_src_path }}"
        dest: "{{ config_file_dest_path }}"
        owner: ansibleadmin
        group: ansibleadmin
        mode: "0644"
